In [1]:
# # Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv(r'C:\InhouseInternship\majorproject7\Test set.csv')

In [3]:
print(dataset)

         Height     Weight     Sex
0    146.323241  59.861065  Female
1    175.695412  77.863687    Male
2    183.216164  72.131992    Male
3    184.245269  77.546000    Male
4    132.302261  55.188496  Female
..          ...        ...     ...
200  155.090314  77.248911  Female
201  149.175907  93.231692    Male
202  168.030874  63.640623  Female
203  172.608090  55.189983    Male
204  145.082128  45.583285  Female

[205 rows x 3 columns]

In [4]:
#Checking Missing values
dataset.isnull().sum()

Height    0
Weight    0
Sex       0
dtype: int64

In [5]:
# # Removing index column
# dataset = dataset.dropna()
dataset

         Height     Weight     Sex
0    146.323241  59.861065  Female
1    175.695412  77.863687    Male
2    183.216164  72.131992    Male
3    184.245269  77.546000    Male
4    132.302261  55.188496  Female
..          ...        ...     ...
200  155.090314  77.248911  Female
201  149.175907  93.231692    Male
202  168.030874  63.640623  Female
203  172.608090  55.189983    Male
204  145.082128  45.583285  Female

[205 rows x 3 columns]

In [6]:
dataset.describe()

           Height      Weight
count  205.000000  205.000000
mean   160.874125   69.927028
std     15.171040   15.462396
min    123.007006   34.726666
25%    148.942667   58.583137
50%    161.749388   69.544469
75%    172.608090   77.964667
max    199.282251  129.410122

In [7]:
# Encoding Categorical data:
# # Encoding the Independent Variable
# from sklearn.preprocessing import LabelEncoder
# labelencoder_X = LabelEncoder()
# X[:, 6] = labelencoder_X.fit_transform(X[:, 6])

In [8]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:,0:2].values
# Extracting dependent variable:
y = dataset.iloc[:, 2].values

In [9]:
# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
labelencoder_y.fit(["Male","Female"])
y = labelencoder_y.fit_transform(y)

In [10]:
print(X)

[[146.3232413   59.861065  ]
 [175.6954121   77.86368697]
 [183.2161637   72.13199162]
 [184.2452685   77.54599954]
 [132.3022607   55.18849649]
 [149.8639136   66.05565459]
 [191.1730884   83.63133864]
 [135.4071744   47.01445695]
 [184.9957625   71.93582824]
 [179.9908867   65.92079489]
 [186.1618374   83.72019383]
 [177.784335    51.59443143]
 [124.5761544   49.49065937]
 [135.0845874   57.01715684]
 [161.783083    63.11811732]
 [147.1984523   74.90954714]
 [168.6195333   68.71086764]
 [180.3799948   58.5831375 ]
 [172.9806484   91.76506667]
 [183.2740005   83.53897404]
 [135.8408238   75.15031468]
 [177.3010401   61.54651   ]
 [170.228071    63.16246219]
 [141.8363614   45.4665998 ]
 [151.4646936   51.1065089 ]
 [150.2536868   56.38212115]
 [123.0070061   66.68550969]
 [170.8142259   72.87114003]
 [179.5604019   93.3795254 ]
 [146.7985959   58.96877805]
 [145.830298    91.71072835]
 [144.981023    70.54812663]
 [139.3907781   58.18591881]
 [182.6131284   90.55450022]
 [178.4496356   65.99284671]
 [173.649627    70.06223697]
 [149.6358087   66.96144199]
 [166.950541    68.60650747]
 [152.9447652   47.80660514]
 [170.0438094   69.52377418]
 [135.7625193   39.98973038]
 [146.4209564   50.66569887]
 [165.4572847   76.9860487 ]
 [159.9314963   69.20584106]
 [173.6478179   85.91706134]
 [162.2114966   53.98530301]
 [171.1970616   96.909219  ]
 [154.2079222   64.10437771]
 [163.8065453   76.4823852 ]
 [152.0791785   70.49920032]
 [173.0748152   77.17787716]
 [164.2692232   61.26559153]
 [156.7976193   68.21134945]
 [157.8895769   92.24610011]
 [180.9764798   95.59478219]
 [175.2433961   77.13018201]
 [155.754493    86.9498469 ]
 [180.0229055   70.90164462]
 [180.3403211   74.10095369]
 [144.4119408   54.01444259]
 [147.2221773   76.70733287]
 [152.7088563   62.79598838]
 [142.3098204   81.7159541 ]
 [166.3135265   88.13290343]
 [163.0913943   78.37616668]
 [167.0077238   62.09138124]
 [143.3310166   71.15222384]
 [161.3907099   75.69117549]
 [167.5388812   99.60316557]
 [169.4368352  107.3581389 ]
 [183.2013182   96.94715589]
 [156.8690279   53.62286242]
 [144.4131961   57.58668498]
 [150.0416855   79.01636867]
 [164.4833362   61.48739535]
 [155.0623811   79.42228181]
 [142.5393447   71.64057998]
 [176.7140956   76.14865542]
 [168.4181785   45.96840161]
 [141.8980545   64.07728905]
 [174.3396578   87.15967177]
 [166.0337181   50.68614841]
 [160.0180625   47.57437511]
 [148.0261077   49.21201967]
 [146.281581    59.47391158]
 [158.8317653   58.396218  ]
 [180.7420372  103.3905654 ]
 [166.3374417  102.142888  ]
 [173.2833883   69.57781786]
 [153.5540268   64.21426629]
 [155.867935    53.30410127]
 [143.9370543   60.91156342]
 [168.0598835   54.91874421]
 [135.2562538   61.76897564]
 [177.2286376   98.22128379]
 [168.4002617   68.27897993]
 [175.8196374   75.6878598 ]
 [147.2088207   71.91470902]
 [143.4101933   70.25466739]
 [184.0023346  101.0296023 ]
 [179.9941395   82.91463154]
 [150.581321    60.71624655]
 [143.9200482   64.63599154]
 [171.5613067   80.86742566]
 [171.0917634   72.24031272]
 [148.1625381   53.33421763]
 [145.2916488   50.31307691]
 [163.7915407   82.67117663]
 [160.3197594   57.52783949]
 [151.8196421   64.80884381]
 [162.6724833   77.96466705]
 [150.3120371   72.23105588]
 [147.9065279   61.23632646]
 [158.5757835   83.6079361 ]
 [161.7493883   69.49571825]
 [160.2908185   57.11077005]
 [158.2419175   85.56107232]
 [178.1444883   92.30898007]
 [158.1862747   77.11418056]
 [152.5895691   34.72666609]
 [131.1273977   73.83481125]
 [154.7959763   74.65321809]
 [183.0966467   64.05785271]
 [157.6740806   44.36280578]
 [172.7391841   74.73017956]
 [138.5758889   75.88078275]
 [177.9294904   77.66715604]
 [163.7204411  129.410122  ]
 [177.9092339  113.2503094 ]
 [142.8596964   58.79075666]
 [134.0932725   60.88158179]
 [139.3309187   50.94727899]
 [161.4693695   45.80117027]
 [159.9630217   75.37583014]
 [158.272415    48.97376511]
 [169.2229144   83.21845422]
 [170.9833661   57.26852227]
 [164.32512     72.10525226]
 [144.9223785   65.81607146]
 [161.3928705   51.19553074]
 [173.213002    85.73721509]
 [160.8713684   49.65055203]
 [162.7634606   54.91954846]
 [171.4205329   80.40997588]
 [171.4610256   68.63804817]
 [164.1230059   41.23383545]
 [168.096226    69.52353258]
 [153.2253068   58.07491316]
 [173.1229682  117.7668917 ]
 [199.2822511   55.75179928]
 [141.8573719   63.648645  ]
 [144.0775791   68.09782933]
 [165.0537385   90.72013328]
 [159.0205698   75.26937521]
 [165.4790635   86.54622202]
 [162.9186952   77.30707502]
 [157.9004943   46.14417081]
 [157.195575    76.05757143]
 [167.4720967   67.67081367]
 [148.9426665   61.95692679]
 [184.6660751   78.14266923]
 [173.7816213   54.46835757]
 [186.5994933   82.19080006]
 [180.5159267   70.42488418]
 [171.1632224   75.07517632]
 [153.5825326   57.01562953]
 [144.3927917   49.66584381]
 [172.5064953   81.79668789]
 [170.9672098   69.54446916]
 [164.8711385   75.46953342]
 [139.0659727   55.14056088]
 [171.0282427   74.7954068 ]
 [147.425025    68.47480543]
 [177.0294219   86.0358905 ]
 [130.7627735   83.81226142]
 [168.0056649   74.08027766]
 [163.7128594   74.58872409]
 [151.000864    85.80413054]
 [188.8522241   69.48378601]
 [176.6875383   86.28422599]
 [144.1749247   61.04539955]
 [190.2616152   97.10252458]
 [133.9827252   61.53940031]
 [177.2710736   75.99564021]
 [178.8946419   78.25158421]
 [141.6464472   61.13619954]
 [152.3723814   73.42231034]
 [178.1315966   48.33299534]
 [170.6105691   54.68173273]
 [182.5356395   70.87055723]
 [151.5163043   71.71782359]
 [171.3453199   59.74839156]
 [149.0946244   61.61322534]
 [154.1159173   82.4932717 ]
 [165.7679235   82.83127696]
 [145.7482346   43.99934018]
 [161.1245625   72.19438206]
 [156.0223093   57.7128837 ]
 [133.2099703   65.67113792]
 [130.8772036   48.49075755]
 [155.0903141   77.24891146]
 [149.1759067   93.23169166]
 [168.0308738   63.64062288]
 [172.6080901   55.18998258]
 [145.0821277   45.5832851 ]]

In [11]:
print(y)

[0 1 1 1 0 0 1 0 1 1 1 1 0 0 0 0 1 1 1 1 0 1 1 0 0 0 0 1 1 0 0 1 0 1 1 1 0
 1 0 1 0 0 0 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 1 1 1 0 0
 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 1 1 0 1 0 1 1 1 0 0 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0
 1 1 0 0 1 1 1 1 0 0 1 0 1 1 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 0 1 1 0 1 0 1 1
 0 1 1 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 1 0]

In [12]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [13]:
print(X_train)

[[132.3022607   55.18849649]
 [156.8690279   53.62286242]
 [158.272415    48.97376511]
 [164.1230059   41.23383545]
 [183.0966467   64.05785271]
 [123.0070061   66.68550969]
 [148.0261077   49.21201967]
 [199.2822511   55.75179928]
 [152.3723814   73.42231034]
 [184.9957625   71.93582824]
 [155.867935    53.30410127]
 [180.5159267   70.42488418]
 [152.7088563   62.79598838]
 [155.0623811   79.42228181]
 [145.2916488   50.31307691]
 [166.3135265   88.13290343]
 [133.2099703   65.67113792]
 [171.4205329   80.40997588]
 [151.4646936   51.1065089 ]
 [145.830298    91.71072835]
 [169.2229144   83.21845422]
 [135.7625193   39.98973038]
 [147.2221773   76.70733287]
 [155.754493    86.9498469 ]
 [150.581321    60.71624655]
 [180.7420372  103.3905654 ]
 [183.2740005   83.53897404]
 [162.9186952   77.30707502]
 [147.2088207   71.91470902]
 [180.9764798   95.59478219]
 [178.8946419   78.25158421]
 [164.2692232   61.26559153]
 [161.3928705   51.19553074]
 [160.8713684   49.65055203]
 [147.9065279   61.23632646]
 [175.8196374   75.6878598 ]
 [163.7915407   82.67117663]
 [168.096226    69.52353258]
 [162.6724833   77.96466705]
 [188.8522241   69.48378601]
 [161.783083    63.11811732]
 [170.8142259   72.87114003]
 [160.3197594   57.52783949]
 [141.6464472   61.13619954]
 [177.9294904   77.66715604]
 [171.1970616   96.909219  ]
 [171.3453199   59.74839156]
 [155.0903141   77.24891146]
 [186.5994933   82.19080006]
 [142.3098204   81.7159541 ]
 [183.2161637   72.13199162]
 [144.4119408   54.01444259]
 [157.6740806   44.36280578]
 [172.7391841   74.73017956]
 [159.9314963   69.20584106]
 [186.1618374   83.72019383]
 [151.8196421   64.80884381]
 [150.0416855   79.01636867]
 [161.1245625   72.19438206]
 [133.9827252   61.53940031]
 [141.8573719   63.648645  ]
 [143.4101933   70.25466739]
 [184.2452685   77.54599954]
 [135.2562538   61.76897564]
 [158.1862747   77.11418056]
 [184.6660751   78.14266923]
 [130.8772036   48.49075755]
 [173.0748152   77.17787716]
 [146.3232413   59.861065  ]
 [177.2286376   98.22128379]
 [158.2419175   85.56107232]
 [168.4002617   68.27897993]
 [163.0913943   78.37616668]
 [171.4610256   68.63804817]
 [146.4209564   50.66569887]
 [169.4368352  107.3581389 ]
 [152.0791785   70.49920032]
 [163.8065453   76.4823852 ]
 [158.8317653   58.396218  ]
 [168.0308738   63.64062288]
 [135.0845874   57.01715684]
 [159.0205698   75.26937521]
 [141.8363614   45.4665998 ]
 [151.5163043   71.71782359]
 [164.32512     72.10525226]
 [135.8408238   75.15031468]
 [147.1984523   74.90954714]
 [168.4181785   45.96840161]
 [179.9941395   82.91463154]
 [144.3927917   49.66584381]
 [172.6080901   55.18998258]
 [191.1730884   83.63133864]
 [167.5388812   99.60316557]
 [146.281581    59.47391158]
 [154.7959763   74.65321809]
 [157.195575    76.05757143]
 [178.1315966   48.33299534]
 [167.4720967   67.67081367]
 [143.9370543   60.91156342]
 [163.7128594   74.58872409]
 [177.784335    51.59443143]
 [152.5895691   34.72666609]
 [143.9200482   64.63599154]
 [173.649627    70.06223697]
 [180.0229055   70.90164462]
 [167.0077238   62.09138124]
 [175.6954121   77.86368697]
 [131.1273977   73.83481125]
 [171.1632224   75.07517632]
 [165.4572847   76.9860487 ]
 [148.1625381   53.33421763]
 [161.4693695   45.80117027]
 [151.000864    85.80413054]
 [180.3799948   58.5831375 ]
 [152.9447652   47.80660514]
 [159.9630217   75.37583014]
 [157.8895769   92.24610011]
 [148.9426665   61.95692679]
 [177.9092339  113.2503094 ]
 [178.4496356   65.99284671]
 [179.5604019   93.3795254 ]
 [161.7493883   69.49571825]
 [144.0775791   68.09782933]
 [144.981023    70.54812663]
 [170.9672098   69.54446916]
 [163.7204411  129.410122  ]
 [144.1749247   61.04539955]
 [139.3907781   58.18591881]
 [172.5064953   81.79668789]
 [162.7634606   54.91954846]
 [145.0821277   45.5832851 ]
 [153.2253068   58.07491316]
 [146.7985959   58.96877805]
 [184.0023346  101.0296023 ]
 [160.0180625   47.57437511]
 [168.0056649   74.08027766]
 [141.8980545   64.07728905]
 [160.2908185   57.11077005]
 [173.1229682  117.7668917 ]
 [156.0223093   57.7128837 ]
 [144.4131961   57.58668498]
 [176.7140956   76.14865542]
 [150.2536868   56.38212115]
 [153.5825326   57.01562953]
 [166.0337181   50.68614841]
 [149.1759067   93.23169166]
 [130.7627735   83.81226142]
 [165.7679235   82.83127696]
 [170.0438094   69.52377418]
 [180.3403211   74.10095369]
 [173.213002    85.73721509]
 [173.2833883   69.57781786]
 [183.2013182   96.94715589]
 [166.3374417  102.142888  ]
 [149.6358087   66.96144199]
 [177.3010401   61.54651   ]
 [179.9908867   65.92079489]
 [171.5613067   80.86742566]
 [145.7482346   43.99934018]
 [161.3907099   75.69117549]
 [149.0946244   61.61322534]
 [178.1444883   92.30898007]
 [154.2079222   64.10437771]
 [147.425025    68.47480543]]

In [14]:
print(X_test)

[[156.7976193   68.21134945]
 [190.2616152   97.10252458]
 [149.8639136   66.05565459]
 [172.9806484   91.76506667]
 [170.6105691   54.68173273]
 [139.0659727   55.14056088]
 [142.5393447   71.64057998]
 [165.4790635   86.54622202]
 [171.0917634   72.24031272]
 [182.6131284   90.55450022]
 [124.5761544   49.49065937]
 [142.8596964   58.79075666]
 [175.2433961   77.13018201]
 [143.3310166   71.15222384]
 [162.2114966   53.98530301]
 [164.8711385   75.46953342]
 [134.0932725   60.88158179]
 [135.4071744   47.01445695]
 [166.950541    68.60650747]
 [165.0537385   90.72013328]
 [174.3396578   87.15967177]
 [150.3120371   72.23105588]
 [139.3309187   50.94727899]
 [171.0282427   74.7954068 ]
 [176.6875383   86.28422599]
 [144.9223785   65.81607146]
 [157.9004943   46.14417081]
 [158.5757835   83.6079361 ]
 [173.7816213   54.46835757]
 [153.5540268   64.21426629]
 [177.2710736   75.99564021]
 [154.1159173   82.4932717 ]
 [138.5758889   75.88078275]
 [177.0294219   86.0358905 ]
 [168.0598835   54.91874421]
 [168.6195333   68.71086764]
 [182.5356395   70.87055723]
 [170.9833661   57.26852227]
 [170.228071    63.16246219]
 [164.4833362   61.48739535]
 [173.6478179   85.91706134]]

In [15]:
print(y_test)

[0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 0 1 1 0 0 0 1 0 1 1 0 1 1 1 1
 1 1 1 1]

In [16]:
print(y_train)

[0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 1 1 1 0 0 1 0
 1 0 1 0 1 0 0 1 1 1 0 1 1 1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 1
 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0
 0 0 1 0 1 1 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 0 1
 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0]

In [17]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier_NB = GaussianNB()
classifier_NB.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier_NB.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

# calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Confusion matrix:
[[16  1]
 [ 2 22]]
Accuracy: 92.68

In [29]:
filename = 'model_nb.pkl'
pickle.dump(classifier_NB, open(filename, 'wb'))

In [18]:
import pickle
print("[INFO] Saving model...")
# Save the trained model as a pickle string.
saved_model=pickle.dump(classifier_NB,open('major_NB.pkl', 'wb'))
# Saving model to disk

[INFO] Saving model...

In [19]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier_KNN= KNeighborsClassifier()
classifier_KNN.fit(X_train,y_train)

# Predicting the Test set results
y_pred = classifier_KNN.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

# calculate Accuracy
#               Y_pred
#             0       1
#          0[64     4(FP)]  Type 1 Error
# y-test   1[3(FN)     29]  Type 2 Error
# Accuracy 64+29/64+4+3+29
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Confusion matrix:
[[17  0]
 [ 2 22]]
Accuracy: 95.12

In [27]:
filename = 'model_knn.pkl'
pickle.dump(classifier_KNN, open(filename, 'wb'))

In [21]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier_DT = DecisionTreeClassifier(criterion = 'entropy', random_state = 42)
classifier_DT.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier_DT.predict(X_test)
print(y_pred)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

[1 1 0 1 0 0 1 1 0 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 1 0 0 1 1 1 1 0 0 1 0 1 1
 0 0 0 1]
Confusion matrix:
[[12  5]
 [ 8 16]]
Accuracy: 68.29

In [28]:
filename = 'model_dt.pkl'
pickle.dump(classifier_DT, open(filename, 'wb'))

In [23]:
# Fitting SVM to the Training set LINEAR
from sklearn.svm import SVC
classifier_linear = SVC(kernel = 'linear', random_state = 0)
classifier_linear.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier_linear.predict(X_test)
print(y_pred)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

# calculate Accuracy
#   0   1
# 0[66  2(FP type 1)]
#1 [8(FN Type 24) 23]
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

[0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 1 1
 1 1 1 1]
Confusion matrix:
[[16  1]
 [ 1 23]]
Accuracy: 95.12

In [30]:
filename = 'model_linear.pkl'
pickle.dump(classifier_linear, open(filename, 'wb'))

In [24]:
import pickle
print("[INFO] Saving model...")
# Save the trained model as a pickle string.
saved_model=pickle.dump(classifier_linear,open('major_SVM_linear.pkl', 'wb'))
# Saving model to disk

[INFO] Saving model...

In [25]:
# Training the Random Forest Classification model on the Training set
from sklearn.ensemble import RandomForestClassifier
classifier_Random = RandomForestClassifier(n_estimators = 200, criterion = 'entropy', random_state = 0)
classifier_Random.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier_Random.predict(X_test)
print(y_pred)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

# calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

[1 1 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1
 1 1 1 1]
Confusion matrix:
[[16  1]
 [ 3 21]]
Accuracy: 90.24

In [31]:
filename = 'model_random.pkl'
pickle.dump(classifier_Random, open(filename, 'wb'))

In [26]:
import pickle
print("[INFO] Saving model...")
# Save the trained model as a pickle string.
saved_model=pickle.dump(classifier_Random,open('major_RF.pkl', 'wb'))
# Saving model to disk

[INFO] Saving model...